multinode: false

# Example tracing configuration - uncomment to enable distributed tracing
# Note: EPP is deployed by GAIE chart in this example, not by modelservice
# tracing:
#   enabled: true
#   otelCollectorEndpoint: "http://otel-collector:4317"
#   samplingRate: 0.1
#   components:
#     routingProxy: true  # Only routing proxy is controlled by this chart
#     vllm: false  # vLLM tracing not yet implemented

modelArtifacts:
  uri: "hf://Qwen/Qwen3-0.6B"
  size: 20Gi
  authSecretName: "llm-d-hf-token"

routing:
  modelName: Qwen/Qwen3-0.6B
  servicePort: 8000
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: infra-kv-events-inference-gateway

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
    connector: nixlv2
    secure: false

  inferenceModel:
    create: false

  inferencePool:
    create: false
    name: gaie-kv-events

  httpRoute:
    create: true

  epp:
    create: false

decode:
  create: true
  replicas: 2
  monitoring:
    podmonitor:
      enabled: false
      portName: "metrics"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: custom
    command:
      - /bin/sh
      - '-c'
    args:
      - |
        vllm serve Qwen/Qwen3-0.6B \
        --host 0.0.0.0 \
        --port 8200 \
        --block-size 64 \
        --prefix-caching-hash-algo sha256_cbor_64bit \
        --enforce-eager \
        --kv-transfer-config '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}' \
        --kv-events-config "{\"enable_kv_cache_events\":true,\"publisher\":\"zmq\",\"endpoint\":\"tcp://gaie-kv-events-epp.llm-d.svc.cluster.local:5557\",\"topic\":\"kv@${POD_IP}@Qwen/Qwen3-0.6B\"}" \
    env:
      - name: PYTHONHASHSEED
        value: "42"
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
    ports:
      - containerPort: 5557
        protocol: TCP
      - containerPort: 8200
        name: metrics
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}

# The prefill replica is disabled via 'create: false' since pd is not
# enabled for this configuration. Advanced P/D examples will follow later.
prefill:
  create: false
