# Creates the resources for simulating llm-d inference
multinode: false

# Tracing configuration example
# Note: EPP is deployed by GAIE chart in this example, not by modelservice
# tracing:
#   enabled: true
#   otelCollectorEndpoint: "http://otel-collector:4317"
#   samplingRate: 0.1
#   components:
#     routingProxy: true  # Only routing proxy is controlled by this chart
#     vllm: false

modelArtifacts:
  uri: "hf://random"
  size: 5Mi

routing:
  # This is the model name for the openai api request
  modelName: random
  servicePort: 8000
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: infra-sim-inference-gateway

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
    connector: nixlv2
    secure: false

  inferenceModel:
    create: false

  inferencePool:
    create: false
    name: gaie-sim

  httpRoute:
    create: true

  epp:
    # use GAIE instead of EPP
    create: false

decode:
  create: true
  replicas: 3
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d-inference-sim:v0.3.0"
    modelCommand: imageDefault
    ports:
      - containerPort: 5557
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    startupProbe:
      httpGet:
        path: /health
        port: 8200
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /health
        port: 8200
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health
        port: 8200
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
  volumes:
  - name: metrics-volume
    emptyDir: {}

prefill:
  create: true
  replicas: 1
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d-inference-sim:v0.3.0"
    modelCommand: imageDefault
    ports:
      - containerPort: 5557
        protocol: TCP
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    startupProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      periodSeconds: 5
      timeoutSeconds: 2
  volumes:
  - name: metrics-volume
    emptyDir: {}
