# Example tracing configuration - uncomment to enable distributed tracing
# tracing:
#   enabled: true
#   otelCollectorEndpoint: "http://otel-collector:4317"
#   samplingRate: 0.1

inferenceExtension:
  replicas: 1
  image:
    # Either image will work, you just need to bring the correct plugins per image. In this example we will bring the upstream default plugin
    ###################
    # name: llm-d-inference-scheduler
    # hub: ghcr.io/llm-d
    # tag: v0.2.1
    ###################
    name: epp
    hub: registry.k8s.io/gateway-api-inference-extension
    tag:  v0.5.1
    ###################
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "default-plugins.yaml" # using upstream GIE default-plugins, see: https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/config/charts/inferencepool/templates/epp-config.yaml#L7C3-L56C33
inferencePool:
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: ms-sim-llm-d-modelservice
